### ISSUE TITLE
Get scans automatically done by USDA

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q-private#50]
Brenda is DISC's OCIO Business Support Representative (BSR). Greg spoke with her previously and she said there were automatic scans done by DISC as part of PaaS.

## Tasks

- [ ] Ping Brenda Theole and ask her how we request the pre-existing scans on our dev/staging server. Could be the scan is only done on the production server. But the production server was set up, so there might be scans.
- [ ] Track scans for sharing as part of our ATO package
- [ ] Start a project in Turbo ATO for Turbo ATO and attach scans
