### ISSUE TITLE
TASK: Update and test more recent jQuery and other assets

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q-private#84]
## Task

Update and test more recent versions of various jQuery and other Javascript and CSS imported libraries. It's been a while since the libraries have been updated.

## Discussion

Javascript and CSS libraries are maintained by the `fetch-vendor-resources.sh` script. The `fetch-vendor-resources.sh` can be updated with newer versions of these libraries, then the script can be run to retrieve the libraries.  The the unit tests can be run to make sure everything is working.

- [ ] Test newer version of jQuery (3.6.0)
- [ ] See what other versions libraries can be updated
- [ ] Test on Chrome, Firefox, Safari, and if possible Edge
